### PR TITLE
New config variable $egAutoCreatePageNamespaces: replace $wgContentNa…

### PR DESCRIPTION
**Pull request by oetterer**
…mespaces as valid points of origin

With this, you have more control over the namespaces, you can use the parser function on. Defaults to all content namespaces.

### CODE REVIEW

**Comment by mkroetzsch** [comment]
Thanks, merged.

**Comment by s7eph4n** [comment]
IMO this changes the interface of the extension and would have required either a fallback to `$wgContentNamespaces` (e.g. when `!isset( $egAutoCreatePageNamespaces )`) or a major version step.

It would also have been great if the new config var were documented in [README.md](/mkroetzsch/AutoCreatePage/blob/master/README.md)

@oetterer Follow-up PR? ;-)

**Comment by oetterer** [comment]
But it defaults to `$wgContentNamespaces` (https://github.com/mkroetzsch/AutoCreatePage/blob/master/AutoCreatePage.php#L36). Isn't that sufficient?

And yes: I totall forgot to document. Will do asap.

**Comment by s7eph4n** [comment]
You are right! Sorry, I did not see that line.
Thanks for #10 !

**Pull request merged**
